### ISSUE TITLE
Provide default URL rule or more helpful exception when routing.build fails due to unspecified arguments

### ISSUE THREAD

**Issue by nathan-rice** [mitsuhiko/werkzeug#140]
In attemping to match a URL rule, I did not find:

```python
raise BuildError(endpoint, values, method)
```
provided sufficient information on exactly what I was doing wrong.  I suggest raising a different exception if

```python
self.map._rules_by_endpoint.get(endpoint, ())
```

is empty versus if none of the endpoints satisfy the requirements.  I had to step through a lot of your code to understand where I had screwed up, but a nice verbose exception message would have put me on the right track immediately.

**Comment by untitaker** [comment]
I think this has been sufficiently fixed by https://github.com/mitsuhiko/werkzeug/pull/691
