### ISSUE TITLE
Rule.empty() downgrades instance to base Rule class

### ISSUE THREAD

**Issue by ods** [mitsuhiko/werkzeug#179]
Sometimes it's useful to subclass `Rule`, e.g. we use such derived class where authentication is required. Starting from some version of werkzeug this doesn't work if we also use `Subdomain`, `Submount` or `EndpointPrefix`. The reason is the implementation of `Rule.empty()` which always creates a copy by instantiating base `Rule` class.

**Comment by untitaker** [comment]
This has been dealt with by https://github.com/mitsuhiko/werkzeug/pull/677. Regarding @jek's concerns, I think there are too many cases where the subclass only changes the behavior, and doesn't add any new fields.
