### ISSUE TITLE
IPv6-related problems with run_simple on "localhost"

### ISSUE THREAD

**Issue by yk4ever** [mitsuhiko/werkzeug#33]
I have a Linux Mint system. Domain name "localhost" is resolved to both "::1" (IPv6) and "127.0.0.1" (IPv4).

When Werkzeug's run_simple binds to "localhost", it uses the first corresponding address - in case of my system, the IPv6 one. But, for some reason, Mozilla Firefox seems to interpret "localhost" as 127.0.0.1 only. Thus, opening "localhost:5000" in Firefox results in error - while in Chrome it works fine.

I think, for the time being, Werkzeug should prefer IPv4 addresses over IPv6 ones when binding to a domain name (or, at least, when binding to localhost).

**Comment by untitaker** [comment]
127.0.0.1 does seem to be the default.
