### ISSUE TITLE
Add setup.py classifiers

### ISSUE THREAD

**Issue by dupuy** [mitsuhiko/werkzeug#403]
On the [main Werkzeug page](http://werkzeug.pocoo.org/) it says:
> Supports Python from 2.4 up to 2.7.

However, in the 0.9 releases, there are several uses of class decorators, which are [only available in Python 2.6 and later](http://python3porting.com/improving.html#class-decorators) (decorators for functions are available in 2.4, but ``@implements_…`` and ``@native_…`` used in Werkzeug are class decorators).

I don't expect you to roll back your use of class decorators - they are nice, you should use them, and when Travis CI drops support for Python 2.5 I won't care anymore whether you support it in what version, but you might want to update the text in the main page to reflect this change in version support.  Seems like every couple of weeks another package we use is dropping support for 2.5, so you're definitely with the trend.

**Comment by vatsala** [comment]
https://github.com/mitsuhiko/werkzeug/pull/719

**Comment by untitaker** [comment]
Fixed by @vatsaia's PR
