### ISSUE TITLE
environment can only contain strings

### ISSUE THREAD

**Issue by segalle** [mitsuhiko/werkzeug#467]
when running runserver_plus i get an error message: "TypeError: environment can only contain strings" (running on windows 7 x64).

i checked the list of the os.environ items and found out that CELERY_LOADER is unicode and not string.

i fixed it by changing this line to:
os.environ.setdefault(str('CELERY_LOADER'), str('djcelery.loaders.DjangoLoader'))

**Comment by untitaker** [comment]
Closing this because it really is not a bug for Werkzeug to work around at.
