### ISSUE TITLE
UserAgent detects ChromeOS as MacOS

### ISSUE THREAD

**Issue by jace** [mitsuhiko/werkzeug#512]
On a Chromebook with the following UA string, `werkzeug.useragents.UserAgent` identifies platform as `macos`. It should be either `cros` (a new entry) or `linux`:

`Mozilla/5.0 (X11; CrOS x86_64 5116.115.4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36`

**Comment by decached** [comment]
Fixed in [0.10](https://github.com/mitsuhiko/werkzeug/blob/a735489293698ffbc990e3c9bb2da50308a683fb/CHANGES#L67)

Can be closed.
