### ISSUE TITLE
Race condition in routing.Map

### ISSUE THREAD

**Issue by methane** [mitsuhiko/werkzeug#546]
Reported [here](http://lists.unbit.it/pipermail/uwsgi/2014-June/007370.html)

routing.Map.update() has race condition.

**Comment by untitaker** [comment]
FWIW this actually uses locks now: https://github.com/mitsuhiko/werkzeug/commit/48037c155b8f0ae74a5f906b38fec170b9b78e69

Just for somebody who comes by to review this.
