### ISSUE TITLE
werkzeug.run_simple re-seed after fork?

### ISSUE THREAD

**Issue by gabor** [mitsuhiko/werkzeug#607]
(werkzeug-0.9.6). i'm using `werkzeug.run_simple` with `processes=4`. the problem is, because it forks on every request, if i use the random-module in python, i always get the same numbers.

it would be nice if werkzeug could call `random.seed()` after every fork.

**Comment by untitaker** [comment]
This seems to be http://bugs.python.org/issue18747, which is fixed for Python 3.
