### ISSUE TITLE
cached_property does not behave like a property

### ISSUE THREAD

**Issue by toddsifleet** [mitsuhiko/werkzeug#616]
* cached_properties can be set, where as a `normal` property would raise an AttributeError.
* when inspecting a class `cached_properties` are treated as methods not properties.
* This is present in all versions of python

**Comment by untitaker** [comment]
Fixed by https://github.com/mitsuhiko/werkzeug/commit/d131a96d27e75dcd69634fc5d4b2592f5ca17493

**Comment by davidism** [comment]
Looking back at this way later, I don't think this was a correct change. `cached_property` did grow to allow set and delete. While its name has "property" it doesn't allow `@p.getter`/`@p.setter`/`@p.deleter` registration, but inheriting from `property` makes it look like those are available. The inspection test that was added used an internal `inspect` method, and the only real difference appears to be that recent Sphinx prefixes it with "property". The private `inspect.classify_class_attrs` function even documents that all other descriptors are called "method". Type checkers don't special case `property` subclasses, so they don't catch that these should be read-only or not.
