### ISSUE TITLE
WSGIRequestHandler.handle() shouldn't silently discard SSL errors

### ISSUE THREAD

**Issue by jdreed** [mitsuhiko/werkzeug#625]
This is arguably a feature request, not a bug:  It would be great if WSGIRequestHandler.handle() did not silently discard SSL errors.  I have a Flask application that uses client certificates for authentication, and was attempting to run it in debug mode with run_simple.  It would consistently fail after the first request, and no amount of logging would reveal anything, until I went into serving.py, and commented out these lines:
```
            if self.server.ssl_context is None or not is_ssl_error():
                raise
```
That finally allowed me to see that PyOpenSSL was in fact throwing an error (because the session id context is not initialized by default, and I was doing renegotiation), but it was really frustrating.

I am not including a patch, because I'm not sure the best way to implement this.  I could see using the logging module, or setting an environment variable, or something.  WSGIRequestHandler doesn't have an __init__ and adding one to support one option seems like overkill, but is a possibility too, I guess.  I'm happy to write the patch and submit a pull request if there's any sort of consensus on the best way to implement it.

**Comment by untitaker** [comment]
@jdreed Are you interested in writing a patch?

**Comment by jdreed** [comment]
Sure, I'll try and find some time over the next week or two and will submit a pull request when I have something.

**Comment by jdreed** [comment]
Not a pull request yet, because I want to test one or two more things, but any objection to a fix of this style:
https://github.com/jdreed/werkzeug/compare/fix_625

**Comment by untitaker** [comment]
Looks fine, please use a simple ``raise`` to preserve the traceback.
