### ISSUE TITLE
Use utf-8 as filesystem encoding under UNIX (was: test_shared_data_middleware fails on python2)

### ISSUE THREAD

**Issue by minusf** [mitsuhiko/werkzeug#635]
this issue is a bit philosophical in nature :)

this is on openbsd (werkzeug 0.9.6, python 2.7.8)

first of all, on openbsd this test fails on both python2 and python3.
i am aware of #428 and maybe if that is fixed, it will also work on openbsd python3.

but i'd like to talk about python2.  here is the trace:
```python
======================================================================
ERROR: test_shared_data_middleware (werkzeug.testsuite.wsgi.WSGIUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/pobj/py-werkzeug-0.9.6/Werkzeug-0.9.6/werkzeug/testsuite/wsgi.py", line 47, in test_shared_data_middleware
    app_iter, status, headers = run_wsgi_app(app, create_environ(p))
  File "/usr/ports/pobj/py-werkzeug-0.9.6/Werkzeug-0.9.6/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
  File "/usr/ports/pobj/py-werkzeug-0.9.6/Werkzeug-0.9.6/werkzeug/wsgi.py", line 567, in __call__
    cleaned_path = cleaned_path.encode(sys.getfilesystemencoding())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)

----------------------------------------------------------------------
```
on linux this test passes fine.  the whole thing blows up here:
```python
wsgi.py:564:
    def __call__(self, environ, start_response):
        cleaned_path = get_path_info(environ)
        if PY2:
            cleaned_path = cleaned_path.encode(sys.getfilesystemencoding())
```
`sys.getfilesystemencoding` on openbsd in python2 does not return 'utf-8',
and that is basically the end of this bug from werkzeug's side.

so now that we have this diagnosed, we can talk about the
test itself: and it seems a bit schizophrenic to me, because the
documentation for `SharedDataMiddleware` states:
```
    Currently the middleware does not support non ASCII filenames.  If the
    encoding on the file system happens to be the encoding of the URI it may
    work but this could also be by accident.  We strongly suggest using ASCII
    only file names for static files.
```
according to this, if it works, it works, good for ya, but the failure of this
test on my machine is expected and well documented :)  in other words,
this test should be allowed to fail, n'est-ce pas?

**Comment by untitaker** [comment]
I think we may already fix this in 0.11. See #674.
