### ISSUE TITLE
python 3 compatability issue routing.build

### ISSUE THREAD

**Issue by veelai** [mitsuhiko/werkzeug#657]
When passing a MultiDict for the parameter values one gets the following error:

<pre>
File "/usr/lib64/python3.4/site-packages/werkzeug/routing.py", line 1607, in build
    valueiter = values.iteritems(multi=True)
AttributeError: 'MultiDict' object has no attribute 'iteritems'
</pre>

I'm not sure, what exactly to do about this. There is the werkzeug._compat.iteritems function imported which seems to be the right thing, if it can handle MultiDicts.

**Comment by untitaker** [comment]
Did you try using the development version of Werkzeug?

**Comment by veelai** [comment]
Not yet, gonna try it right now.

**Comment by veelai** [comment]
This seems to be fixed in master.

**Comment by untitaker** [comment]
Glad to hear. BTW we hope to get a release out next wednesday

**Comment by veelai** [comment]
Sounds cool. Thanks for all the work. :)
