### ISSUE TITLE
What happened with v0.9.7?

### ISSUE THREAD

**Issue by cvrebert** [mitsuhiko/werkzeug#661]
v0.10 is now out, but v0.9.7's changelog entry still has no release date:
https://github.com/mitsuhiko/werkzeug/blob/6bf548bac6720786ab9440b24ee85b59a7cd267e/CHANGES#L69

**Comment by untitaker** [comment]
Why did you close this?

**Comment by jab** [comment]
Also wondering if http://werkzeug.pocoo.org/docs/0.10/changes/#api-changes is missing an entry for 0.10. If so, let me know if you want a new issue opened for that.

**Comment by untitaker** [comment]
That's because there were no compat-breaking changes, as far as I can remember. Well, apart from the builtin server, but I think that's not important.

**Comment by untitaker** [comment]
Argh, there is no 0.9.7. I doubt that there ever will be one too.
