### ISSUE TITLE
Ability to specify locations to watch

### ISSUE THREAD

**Issue by joostdevries** [mitsuhiko/werkzeug#662]
When I upgraded werkzeug to 0.10.0, reloading stopped working for my app. In addition to this, when using stat, CPU usage is huge even with an interval of 5. 

If I use werkzeug 0.9.6, CPU usage decreases with about 50% and reloading works.

**Comment by untitaker** [comment]
Which version of watchdog are you using?

**Comment by joostdevries** [comment]
0.8.3

**Comment by untitaker** [comment]
There is no such release on PyPI. The dev version from GitHub seems to work fine for me too.

**Comment by joostdevries** [comment]
@untitaker just edited :$ was 0.8.2

**Comment by untitaker** [comment]
Hmm, in which way does it not work for you? Could you give me an exact testcase? Note that the behavior of the reloader might have changed, regarding to how much files it watches (it mostly restricts itself to *.py files nowadays)

**Comment by joostdevries** [comment]
@untitaker doing `touch app.py` would not trigger reload, nor would actually modifying file content. I'm completely rebuilding my virtualenv now because for some reason it's not picking up watchdog right now..

**Comment by joostdevries** [comment]
This must have been a glitch in my virtualenv because now it works fine.. Sorry about that.

**Comment by untitaker** [comment]
No problem.

**Comment by joostdevries** [comment]
@untitaker So I tracked this down a little further and it turns out that it's because I'm using a vagrant box with an NFS volume with the app. inotify cannot detect changes in network volumes so that's the reason this isn't working.

I am curious about one thing: What's the reason that everything in site-packages is also wachted? Because for a fairly large app with lots of deps, this makes a stat loop extremely expensive.

**Comment by untitaker** [comment]
I can't find the exact issue numbers, but the reloader used to watch too little/break in weird edge cases, so we decided to... watch more instead. Maybe we overdid it, but if the inotify reloader doesn't break in edge cases *and* is fast, that's obviously a win.

**Comment by joostdevries** [comment]
@untitaker I could create a PR with a `reloader_paths` param which defaults to `sys.path`. I can imagine quite a few people use docker or vagrant to avoid installing all the deps for every app on their system so `watchdog` won't be an option then. And when you've got as many files in your `site-packages` as I have the stat loop is extremely expensive

**Comment by untitaker** [comment]
Well, I wouldn't use any of werkzeug.serving for production to begin with. Actually implementing a production-ready reloader is as much out of the scope as having a production ready server in Werkzeug... also, this problem doesn't occur to me since I explicitly restart the services in my deploy scripts (fabric in my case).

**Comment by joostdevries** [comment]
@untitaker I wasn't talking about production ;-). I have a mac with a Vagrant box for my app (so I don't have to install redis, pg, rabbitmq etc on my mac). I then mount the `src` folder from my mac fs in the vagrant box using nfs.

**Comment by untitaker** [comment]
Have you tried the reverse -- mounting part of the vagrant box on the host?

**Comment by joostdevries** [comment]
I haven't but it appears to be possible, although it's not quite as easy as the default shared folders setup with vagrant/virtualbox. For now, I'll just do manual restarts but I can imagine more people will run into this issue when they try the new reloader (most devs I know use vagrant or docker for local development).

**Comment by untitaker** [comment]
I am not sure about other solutions. I suppose the reloader could be composed of two parts: One thing that finds the relevant files/folders, another thing that actually watches them. If you want to avoid watching particular files/folders, you would have to provide each of them manually. Is that an acceptable solution?

**Comment by joostdevries** [comment]
@untitaker Yup. For me a solution where I can provide a custom list of folders to watch would be perfect.  The default could then still be `sys.path` as it is now.
