### ISSUE TITLE
Request.mimetype should be always lowercase

### ISSUE THREAD

**Issue by KarelJakubec** [mitsuhiko/werkzeug#670]
As discused in https://github.com/mitsuhiko/flask/issues/1330 mimetype property of request is case insensitive (defined in http://tools.ietf.org/html/rfc2045). It is a rule of thumb that it is lowercase but APPLICATION/JSON is valid as well. Werkzeug currently copies value from header without any conversion to lower/uper case which may cause troubles in code using it.

The result of previous discussion was that Werkzeug should convert mimetype to lowercase. As I walked through the code, the question is whether this shoul hold for content_type as well as it is often computed from mimetype.

**Comment by untitaker** [comment]
@KarelJakubec Would you be interested in writing a pull request? :)

**Comment by KarelJakubec** [comment]
Yeah, it's on my TODO list. It is not as simple as in Flask, there are small if-spagheti around obtaining the mimetype from request so once I have a free evening, I will try to fix it. :)

**Comment by untitaker** [comment]
BTW I think of making ``mimetype`` a property with getter and setter.

**Comment by overdosyu** [comment]
@KarelJakubec and @untitaker, this is my first commit for open source project. Hope you won't mind that I took over this task, and it will be great if you guys can review the code for me, thanks.

**Comment by KarelJakubec** [comment]
Hi @overdosyu, 
thanks for providing the patch. I am not werkzeug nor python expert but I think a bit more work is needed as the patch currently makes mimetype lowercase only FileStorage class. There is more of mimetype for example in CommonRequestDescriptorsMixin (werkzeug/wrappers.py:1612) and CommonResponseDescriptorsMixin(werkzeug/wrappers.py:1655). The ...Request... is pretty straightforward, but ...Response... uses with defining fnc then setting is as a property and then deleting it. Once I really hated Perl for allowing this kind of stuff and thought Python will make my day ...:)

Anyway, I cannot merge it, @untitaker is the chosen one. Could he be so kind to tell us, whether this apporach is acceptable for him? And maybe whether it is needed to update the Response as well. I would say if Request is always converted to lowercase, Response will be lowercase as well unless someone explicitely set it to UPPERCASE on purpose (which should be allowed).

**Comment by untitaker** [comment]
Yeah, the style Werkzeug defines properties is a bit irky and probably has had some historical reason. It has no relevance now, but it doesn't irk me either.

Sorry, I don't get any notification about new commits in https://github.com/mitsuhiko/werkzeug/pull/686, @overdosyu please always comment if you think this is ready to review again.

I am not sure what the proper fix should be... I think it should be left to the developer to control lower vs. uppercase of their headers. Would you agree @KarelJakubec, and is this ready to merge?

**Comment by KarelJakubec** [comment]
As I see there is merged pull request I am closing the issue. 

@overdosyu and @untitaker Thank you guys.
