### ISSUE TITLE
use of type(...) for comparison

### ISSUE THREAD

**Issue by Midnighter** [mitsuhiko/werkzeug#683]
In several places, `werkzeug` uses `type(...) is ...` for comparison, for example, 

```bash
> grep -R 'type([a-zA-Z]*) is' werkzeug
werkzeug/contrib/lint.py:    if type(obj) is not str:
werkzeug/contrib/lint.py:        if type(environ) is not dict:
werkzeug/contrib/lint.py:        if type(headers) is not list:
werkzeug/contrib/lint.py:            if type(item) is not tuple or len(item) != 2:
werkzeug/contrib/lint.py:            if type(name) is not str or type(value) is not str:
werkzeug/debug/repr.py:            if type(obj) is base:
werkzeug/debug/repr.py:    elif type(obj) is base:
werkzeug/http.py:    >>> type(d) is dict
werkzeug/serving.py:            assert type(data) is bytes, 'applications must write bytes'
```

That's less than ideal since it disallows any classes that inherit from the base classes. Specifically, the last one `assert type(data) is bytes, 'applications must write bytes'` bit me when I was using `bytes` from the `future` package for Python 2&3 compatibility. 

It'd be much better to replace all those cases with `isinstance` that also evaluates to `True` for subclasses. I can submit a pull request if you want since it seems rather easy.

This was gleaned from the current master.

**Comment by DasIch** [comment]
We are not unaware of the differences  between isinstance() and type(). Not every type(...) is ... can be replaced with an isinstance call.

Which is not to say that in some of these cases it wouldn't be possible but that should be the exception, if indeed there is actually such a case.

**Comment by untitaker** [comment]
What Daniel said, also I consider the futures module to be completely broken if it doesn't use the exact native types and subclasses instead.

**Comment by Midnighter** [comment]
future uses native types in Python 3 but often different classes when it backports functionality to Python 2. I can't say why they do so. Similarly, I respect your work on werkzeug and I don't have the insight to tell why you've chosen to strictly check for types. Just letting you know that it causes some trouble and I wonder why it's the case when Python usually goes for duck typing.

**Comment by DasIch** [comment]
So I've just checked what the future module actually does. Turns out it's bytes() object is a subclass of bytes() on Python 2 that behaves more or less like bytes() in Python 3.

Even if we were to allow subclasses, you still couldn't use this subclass.

**Comment by untitaker** [comment]
It depends. We could allow it for a few APIs where all Werkzeug does is decode or something like that.

**Comment by Midnighter** [comment]
At the moment the only working option for me is to `str.encode("utf-8")` which returns `bytes` on Python 3 and `str` on Python 2. Since `bytes` is pretty much just an alias for `str` on Python 2 this passes the assertion in werkzeug. Using the `bytes` from `future` would return proper `bytes`. It's nitpicking, I know, but seems cleaner.

**Comment by untitaker** [comment]
It's debatable whether the way Python 3 represents bytes is the "proper" one, but anyway, I think it's terrible to have two ways to represent bytes in one runtime. Especially if one of them advertizes itself as being compatible with the other, when in fact it isn't -- There are very large differences in behavior between Python 2's and 3's ``bytes``.

**Comment by RonnyPfannschmidt** [comment]
going back to the original issue - all uses of is in those places are on purpose
and the place in serving looks like it could be relaxed to a isinstance check
@Midnighter could you test if the code in serving will work with the bytest from the future packages?
and if it does submit a pull request for using isinstance and adding a comment why the fuzzy check is fine?

**Comment by Midnighter** [comment]
In the process of doing this, I ran the full test suite and stumbled over two `UnicodeEncodeError`s. One of them is the same as in #428 and #635 but the other one is new as far as I can tell. I'll attach the output and you can tell me if I should open a separate issue for that. I used tox to test Python 2.6, 2.7, 3.3 and 3.4.

```bash
========================================= FAILURES ==========================================
___________________________ TestTraceback.test_filename_encoding ____________________________

self = <tests.test_debug.TestTraceback object at 0x7fc2199d9048>
tmpdir = local('/tmp/pytest-8/test_filename_encoding0')
monkeypatch = <_pytest.monkeypatch.monkeypatch object at 0x7fc2199d9438>

    def test_filename_encoding(self, tmpdir, monkeypatch):
\x1b[1m>       moduledir = tmpdir.mkdir('f\xf6\xf6')\x1b[0m

tests/test_debug.py:217: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = local('/tmp/pytest-8/test_filename_encoding0'), args = ('f\xf6\xf6',)
p = local('/tmp/pytest-8/test_filename_encoding0/f\xf6\xf6')

    def mkdir(self, *args):
        """ create & return the directory joined with args. """
        p = self.join(*args)
>       py.error.checked_call(os.mkdir, getattr(p, "strpath", p))
E       UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-40: ordinal not in range(128)

/home/beber/.virtualenvs/sijax3/lib/python3.4/site-packages/py/_path/local.py:437: UnicodeEncodeError
________________________________ test_shared_data_middleware ________________________________

tmpdir = local('/tmp/pytest-8/test_shared_data_middleware0')

    def test_shared_data_middleware(tmpdir):
        def null_application(environ, start_response):
            start_response('404 NOT FOUND', [('Content-Type', 'text/plain')])
            yield b'NOT FOUND'
    
        test_dir = str(tmpdir)
\x1b[1m>       with open(path.join(test_dir, to_native(u'\xe4\xf6\xfc', 'utf-8')), 'w') as test_file:\x1b[0m
            test_file.write(u'FOUND')
E           UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-45: ordinal not in range(128)

tests/test_wsgi.py:36: UnicodeEncodeError
```

**Comment by RonnyPfannschmidt** [comment]
that does look like a bad interaction with py.test paths
it's certainly a separate issue do the errors arise for all python versions or just specific ones?

**Comment by RonnyPfannschmidt** [comment]
at first glance the errors on Travis are unrelated,

i'm leaning a bit towards keeping the assertion,
but i not opposed to the type-error,
can someone else make a decision

**Comment by Midnighter** [comment]
These two happen for all versions, Python 3.4 has one additional failure. Let me post a full test log in a separate issue.

**Comment by untitaker** [comment]
Can this be closed?
