### ISSUE TITLE
BuildErrors could be more informative

### ISSUE THREAD

**Issue by Frozenball** [mitsuhiko/werkzeug#688]
The exceptions we currently have are looking like this:
````
BuildError: ('users.view_user', {'view': 'simple'}, 'GET')
````

What I would like to see instead:
````
BuildError: No route found for 'users.view_user' with parameters {'view': 'simple'}. Did you forget to add parameter "id"?
````

or 

````
BuildError: No route found for 'users.view_user' with parameters {'view': 'simple'}. Did you mean 'user.view_user' instead?
````

I'm not saying the exception we currently have are technically wrong but I'm arguing it's bad user experience.

**Comment by untitaker** [comment]
I agree that the current errors are bad, but neither of your suggestions are easy to implement. Especially the latter, it probably requires an algorithm for calculating the Levenshtein distance?

**Comment by RonnyPfannschmidt** [comment]
the first one seems like a good easy task for someone new,
the second one is something extended for a interested 3rd party

**Comment by Frozenball** [comment]
Python has a great sequence similarity algorithm built-in, e.g.
````python
import difflib
print difflib.SequenceMatcher(None, 'users.view_user', 'user.view_user').ratio() # 0.965517241379
````

**Comment by untitaker** [comment]
Ok, that's interesting.
