### ISSUE TITLE
`url_for` with a tuple does not work!

### ISSUE THREAD

**Issue by malev** [mitsuhiko/werkzeug#709]
Code example:

```python
#...
@blueprint.route('/<value:val>/')
def settings(value):
#...

#...
class SettingsConverter(BaseConverter):
    def to_url(self, value):
        return '%s/%s' % (value[0], value[1])
#...

value = ('username', 'project1')
url = url_for('.settings', val=value)
# url will be "u/s" instad of "username/project1"
```
At some point we are loosing the second element of the **tuple** and I'm pretty sure it happens here: https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/routing.py#L1712-L1716

## Versions
- python 2.7
- werkzeug 0.10

Maybe @tswicegood can provide more information.

**Comment by tswicegood** [comment]
The example above leaves out the `to_python()` code that can get to this state.  I've posted [a gist][1] with this example.  This relies on Flask, but swapping out the Werkzeug underneath triggers the error.  To test, run the example and load `http://localhost:5000/foo/bar/`.  As of 0.9.6 (last I had handy), it returns `/foo/bar/`, but as of 0.10.1 it returns `/f/b/`.

[1]: https://gist.github.com/tswicegood/be35921386651103337e

**Comment by tswicegood** [comment]
Err -- sorry, the error state is `/f/o/`, which is even worse as my second value is completely gone.

**Comment by untitaker** [comment]
All of this has been caused by #660, looking into it.

**Comment by untitaker** [comment]
Well, this is quite an awkward situation. As noted [here](https://github.com/mitsuhiko/werkzeug/issues/658#issuecomment-72022911), lists can be (intentionally) used for multiple query values.

I guess what happened then is that, since we switched to MultiDict, both lists and tuples are now accepted as a notation for multiple values (since MultiDict behaves like that).

I think I'll just reverse #660.

**Comment by tswicegood** [comment]
Well, at least I'm not entirely crazy.  I ended up on that same test, but I wasn't 100% sure on it.  It seems like the behavior of #660 is good if there's a way to keep it around.  There is a work around for getting the correct URL, it's `url_for("handler", foo=[foo])`.

Is there a situation where you might ever hand a non-`MultiDict` object that has multiple values where you want those treated like a dictionary?

**Comment by untitaker** [comment]
>Is there a situation where you might ever hand a non-MultiDict object that has multiple values where you want those treated like a dictionary?

You mean literally using a dictionary as a value (`url_for(..., foo=dict(...))`)?

**Comment by untitaker** [comment]
Check out https://github.com/mitsuhiko/werkzeug/pull/710

**Comment by tswicegood** [comment]
Awesome!  Thanks, @untitaker.
