### ISSUE TITLE
is_resource_modified and make_conditional don't seem to work

### ISSUE THREAD

**Issue by jschrewe** [mitsuhiko/werkzeug#744]
I'm trying to load files from mongo db. After setting the headers on the response like so

```python
response.set_etag(outfile.md5)
response.last_modified = outfile.upload_date
```

Google Chrome will never receive a 304 response status. The reason is that it uses the `If-Modified-Since` header and ignores ETags. Werkzeug in turn uses only ETags if an ETag is set on the response object and ignores modification dates that match even if the request does not have a `If-None-Match` header.

If this is the intended behaviour it would probably be a good idea to document it. Well, it would have saved me a couple hours.

**Comment by jschrewe** [comment]
Right. After spending a bit more time with this:

The problem is that Python 3 doesn't use `__nonzero__()` but expects `__bool__()`. But `werkzeug.datastructures.ETags` only has a `__nonzero__()` method. That makes this part of `is_resource_modified` pretty useless.

```python
if etag:
        if_none_match = parse_etags(environ.get('HTTP_IF_NONE_MATCH'))
        if if_none_match: # <- Always true in Python 3
            unmodified = if_none_match.contains_raw(etag)
```

I'm happy to make a pull request. Although it does seem like adding a `__bool__()` method to ETags is a bit trivial for a pull request.

**Comment by untitaker** [comment]
Thanks for investigating this, fixed!
