### ISSUE TITLE
There is no way to access the Request raw data

### ISSUE THREAD

**Issue by devilicecream** [mitsuhiko/werkzeug#745]
There is no way to access the HTTP request in raw format, after it is parsed into a Request object. This makes it difficult to implement for example a middleware to report errors happened during the request code execution.
Serializing the Request object in something readable is an alternative, but I think that caching the raw request in the Request object is simpler and cleaner.

**Comment by untitaker** [comment]
WSGI servers don't expose the raw HTTP request to Werkzeug. The most low-level stuff you'll be able to get out of Werkzeug or Flask can be found in the `environ` property.
