### ISSUE TITLE
Werkzeug debugger should not allow execution of arbitrary code by default

### ISSUE THREAD

**Issue by Frozenball** [mitsuhiko/werkzeug#746]
I think it's too easy to accidentally expose your development environment to public without realising that at the same time you are allowing [unlimited remote access to your computer](http://werkzeug.pocoo.org/docs/0.10/debug/). For example when you are testing the application on mobile devices or when running nginx configuration.

This is why I would propose restricting the eval access of debugger to 127.0.0.1 only (showing tracebacks would remain the same to other addresses). This change wouldn't affect most people. The remaining 1% can always configure this explicitly if needed.

**Comment by RonnyPfannschmidt** [comment]
the default is already false, supporting a variant that allows to filter the valid hosts seems interesting,

could you perhaps propose a patch?

**Comment by mitsuhiko** [comment]
Next release will include a PIN check for the debugger.

**Comment by Frozenball** [comment]
http://labs.detectify.com/post/130332638391/how-patreon-got-hacked-publicly-exposed-werkzeug

>
