### ISSUE TITLE
fix BaseRequestHandler.log (remove datetime duplicate in log output)

### ISSUE THREAD

**Issue by ThomasWaldmann** [mitsuhiko/werkzeug#75]
See there, would be nice if we could remove that monkeypatching:

http://hg.moinmo.in/moin/2.0/file/e6f585ac9766/MoinMoin/util/monkeypatch.py

**Comment by untitaker** [comment]
I think the logging format of Werkzeug's builtin server is supposed to match something else's. You can pass your custom request handler subclass to to run_simple too (`request_handler` param), so I don't think a monkeypatch is needed either.
