### ISSUE TITLE
Logging to stderr

### ISSUE THREAD

**Issue by richburdon** [mitsuhiko/werkzeug#750]
Werkzeug logs all requests to stderr. In a Flask application configuring the workzeug log does not inhibit the HTTP request logging (which still goes to stderr); e.g., 

logging.config(...)

Only affects the non-HTTP werkzeug logging messages.

2015-07-28 16:01:29,691 [  werkzeug|_internal.py    ][INFO]  * Detected change in 'main.py', reloading
2015-07-28 16:01:29,723 [  werkzeug|_internal.py    ][INFO]  * Restarting with stat
127.0.0.1 - - [2015-07-28 16:15:39] "GET / HTTP/1.1" 200 460 0.302674
127.0.0.1 - - [2015-07-28 16:15:40] "GET /res/css/main.css HTTP/1.1" 304 183 0.014869

(BTW, there are DOZENS of stackexchange questions about this). Like this one:
http://stackoverflow.com/questions/17743019/flask-logging-cannot-get-it-to-write-to-a-file

**Comment by hbrls** [comment]
I failed to see werkzeug logs in my Flask app after sorts of configs. Did you mean that the log is written to stderr, not to stdin? I've never thought of that.

**Comment by untitaker** [comment]
Werkzeug's logger has no knowledge of Flask's. Also you shouldn't use the Werkzeug server in production.

This is working as intended, I think.

On 28 July 2015 22:17:25 CEST, Rich Burdon <notifications@github.com> wrote:
>Werkzeug logs all requests to stderr. In a Flask application
>configuring the workzeug log does not inhibit the HTTP request logging
>(which still goes to stderr); e.g., 
>
>logging.config(...)
>
>Only affects the non-HTTP werkzeug logging messages.
>
>2015-07-28 16:01:29,691 [  werkzeug|_internal.py    ][INFO]  * Detected
>change in 'main.py', reloading
>2015-07-28 16:01:29,723 [  werkzeug|_internal.py    ][INFO]  *
>Restarting with stat
>127.0.0.1 - - [2015-07-28 16:15:39] "GET / HTTP/1.1" 200 460 0.302674
>127.0.0.1 - - [2015-07-28 16:15:40] "GET /res/css/main.css HTTP/1.1"
>304 183 0.014869
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/werkzeug/issues/750

-- 
Sent from my phone. Please excuse my brevity.
