### ISSUE TITLE
Migrate to new Travis CI (container based) infrastructure

### ISSUE THREAD

**Issue by jaapz** [mitsuhiko/werkzeug#751]
I was working on my UWSGICache PR and saw that Travis CI was complaining that the werkzeug CI jobs are running on legacy infrastructure.

The exact warning:

    This job ran on our legacy infrastructure. Please read our docs on how to upgrade

Which links to [this documentation page](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade).

**Comment by untitaker** [comment]
I suppose that's because our travis config tries to install the latest pypy. I'm not sure if that's necessary.

On 1 August 2015 15:00:45 CEST, Jaap Broekhuizen <notifications@github.com> wrote:
>I was working on my UWSGICache PR and saw that Travis CI was
>complaining that the werkzeug CI jobs are running on legacy
>infrastructure.
>
>The exact warning:
>
>This job ran on our legacy infrastructure. Please read our docs on how
>to upgrade
>
>Which links to [this documentation
>page](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/werkzeug/issues/751

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
I don't get this warning on other Werkzeug builds. God knows what Travis is up to.
