### ISSUE TITLE
FileSystemCache don't delete files

### ISSUE THREAD

**Issue by yoyoprs** [mitsuhiko/werkzeug#765]
Version: 0.10.4
Cache dir is setted to /tmp
Files cache has been correctly created, but with cache.delete() nothing is deleted

**Comment by untitaker** [comment]
The cache catches IOErrors. Check whether the directory has the correct rights set, or remove the IOError temporarily to see what is going on.

On 2 September 2015 21:55:27 CEST, yoyoprs <notifications@github.com> wrote:
>Version: 0.10.4
>Cache dir is setted to /tmp
>Files cache has been correctly created, but with cache.delete() nothing
>is deleted
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/werkzeug/issues/765

-- 
Sent from my phone. Please excuse my brevity.

**Comment by yoyoprs** [comment]
it seems that this is not the right hash returned by _get_filename, I continue to investigate ...

**Comment by untitaker** [comment]
@yoyoprs Any update on this?

**Comment by yoyoprs** [comment]
Sorry, i do a back shortly

**Comment by yoyoprs** [comment]
after investigating everything works fine, I was deceived by the default cache timeout is not spread from flask-cache to the filesystem class, sorry.
You can close this ticket, thank's for your time.
