### ISSUE TITLE
ProxyFix should respect X-Forwarded-Proto header

### ISSUE THREAD

**Issue by torotil** [mitsuhiko/werkzeug#779]
Currently the ProxyFix doesn't solve the issue of HTTPS-offloading. To solve that it would need to respect the `X-Forwarded-Proto` header. In this case there are no security concerns, but the application is still unable to derive correct absolute URLs.

**Comment by untitaker** [comment]
It does respect that header. Check if your proxy sends that header correctly.

**Comment by torotil** [comment]
True - sorry for the noise.
