### ISSUE TITLE
The UserAgents are not detected correctly Safari 7.0

### ISSUE THREAD

**Issue by shuisman** [mitsuhiko/werkzeug#787]
python: 2.7
werkzeug: 0.9

The UserAgents are not detected correctly (werkzeug/werkzeug/useragents.py)

If you lookup "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A" then Werkzeug gives back the build number instead of the version
* platform: macos
* browser: safari
* version : 7046A194A

**Comment by grahamlyons** [comment]
Looks looked it was fixed in this commit: 13192fb7a9b0c2f8c33704449726f61ec518edf2
