### ISSUE TITLE
flask request.json is causing a HTTP 400 Bad request error without any exception thrown on GET requests

### ISSUE THREAD

**Issue by ye** [mitsuhiko/werkzeug#790]
One of the gotchas I encountered using Flask / Werkzeug is that using GET to hit an API endpoint and access `json` attribute of the request object like this `from flask import request; request.json` would get a generic HTTP 400 Bad request error without any exception thrown. It was really hard to track down what went wrong initially. It would be more explicit and clearer to at least throw an exception to say that GET request can't not have request body etc.

Since the request object in Flask is essentially a wekzeug local proxy, I am filing the ticket here instead on Flask's repo.

 * Python version: 3.4.3
 * Flask version: 0.10.1
 * Werkzeug version: 0.10.4

**Comment by davidism** [comment]
Please edit your report to include an example that produces the problem.  I'm guessing you tried to access `json` without setting the content type of the request.

**Comment by untitaker** [comment]
@ye If you don't expect a request body, why do you try to access it?

**Comment by untitaker** [comment]
Also the json attr is defined inside flask, so the feature request of more detailed error messages only applies to Flask.

**Comment by untitaker** [comment]
I'm closing this because something like this has already been implemented in the master version of Flask.

**Comment by ye** [comment]
@untitaker care to elaborate which line in Flask master that has implemented a more friendly exception?

@davidism it was a bug that I stumbled upon after wasting too much time on until I realized that request.json just won't make sense for GET requests, regardless content-type.

**Comment by untitaker** [comment]
https://github.com/mitsuhiko/flask/blob/master/flask/wrappers.py#L179

**Comment by ye** [comment]
@untitaker thank you.
