### ISSUE TITLE
Remove routing path from Map

### ISSUE THREAD

**Issue by nallath** [mitsuhiko/werkzeug#796]
Is  there a specific reason why it's not possible to remove previously added routes from the Map? I want to create a dynamic system where certain nested objects generate a route. In these cases it can happen that the route is changed (or even stops to exist).

I could make a work around for this fairly simply, but this would require messing with private members, which I'd rather not do. Another option would be for me to add the function upstream, but before doing that, I'd like to know if there are any fundamental reasons for not adding the feature in the first place.

**Comment by davidism** [comment]
Don't use routes this way.  If you need "dynamic" routing, you write a rule with converters to capture variables, then do something with those variables in the view function.  For example, you capture an id that describes an object, rather than making a route for each id.

**Comment by mitsuhiko** [comment]
Because that just fundamentally makes no sense given the constraints with thread safety.

**Comment by nallath** [comment]
Could you explain how this would impact thread safety? You could solve that with locks. Even if you didn't do this, python is generaly quite thread safe.

@davidism:
I looked into doing this, but how would you solve this case;
objects/{objects_id}/foos/{foo_id} 
It makes little sense for the foo object to also be forced to do something with the objects_id, which is the case now. Might be that I'm overlooking something, but I'd go as far that it's good OO practice to not have foo know about the object_id that it's part of.

**Comment by mitsuhiko** [comment]
@nallath the moment you lock the entire thing you might as well create new maps from scratch.  Will be about the same in terms of performance and then you can get away without locks.

**Comment by davidism** [comment]
@nallath if you can identify the foo without knowing the object, then just do that.  Or use the object as further validation: "I'm dealing with this object, so make sure I'm dealing with foos belonging to it".  The solution you're asking for isn't necessary.
