### ISSUE TITLE
werkzeug 0.11 reload + SSL fail

### ISSUE THREAD

**Issue by xgerman** [mitsuhiko/werkzeug#803]
I am getting the following error when using SSL together with reload:

Code:
serving.run_simple(hostname='foo',
                       port='bar',
                       application=server.app,
                       use_debugger=CONF.debug,
                       ssl_context=ctx,
                       use_reloader=True,
                       extra_files='baz'])

Error (Excerpt)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 406, in wrap_socket
    ssl_version=self._protocol, **kwargs)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 211, in __init__
    socket.__init__(self, _sock=sock._sock)
AttributeError: '_socket.socket' object has no attribute '_sock'
---

It seems that the SSL context gets wrapped twice when an SSL context and reload=True is specified. Once on the original socket and then again on the one in the reload context -- but I am not 100% sure.

**Comment by mitsuhiko** [comment]
This will be fixed with the next maintenance release.
