### ISSUE TITLE
Wekrzeug on Flask debug mode raise TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by bagol** [mitsuhiko/werkzeug#804]
I'm running these version Werkzeug==0.11 with Flask==0.10.1 on Python 3.5.0

TypeError raised on line 96 from [werkzeug/debug/__init__.py](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/debug/__init__.py)

```python    
    h.update('cookiesalt')
    cookie_name = '__wzd' + h.hexdigest()[:12]
```

It said there that *Unicode-objects must be encoded before hashing*. So, I tried to change source
code like this:

```python
    cookiesalt = 'cookiesalt'
    h.update(cookiesalt.encode())
    cookie_name = '__wzd' + h.hexdigest()[:12]
```

Then the server can run.

I don't know if what I did is the right thing, since I don't understand how werkzeug internally works. Maybe it is a bug?

**Comment by shuoli84** [comment]
Same here.

**Comment by mortodeg** [comment]
Duplicate of #798

**Comment by mitsuhiko** [comment]
Fixed in 0.11.1

**Comment by SoftpymesAdrian** [comment]
Hey, i'm have the same problem, but i'm already on werkzeug 0.11.6 ---  what should i do?

**Comment by untitaker** [comment]
See #897

**Comment by SoftpymesAdrian** [comment]
Thanks!
