### ISSUE TITLE
Bad File Descriptor when trying to set socket to be inherited in windows

### ISSUE THREAD

**Issue by Socialery** [mitsuhiko/werkzeug#805]
```
> py -3.4 blog.py  # Same for -3.5
Traceback (most recent call last):
  File "blog.py", line 8, in <module>
    app.run(debug=True)
  File "C:\Python34\lib\site-packages\flask\app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "C:\Python34\lib\site-packages\werkzeug\serving.py", line 666, in run_simple
    os.set_inheritable(s.fileno(), True)
OSError: [Errno 9] Bad file descriptor
```

from socket.socket.fileno's documentation

> Under Windows the small integer returned by this method cannot be used where a file descriptor can be used

which I think might be causing the issues, I'm pretty sure this is implying that windows is returning the socket handle as opposed to the file descriptor

I think the solution would be along the lines of

```python
if hasattr(os, 'set_inheritable'):
    if os.name == 'nt':
        os.set_handle_inheritable(s.fileno(), True)
    else:
        os.set_inheritable(s.fileno(), True)
```

but I've yet to run this against the tests, which I'm attempting now

- - -

For convenience:

* https://docs.python.org/3.5/library/socket.html#socket.socket.fileno
* https://docs.python.org/3.5/library/os.html#fd-inheritance

**Comment by Socialery** [comment]
from https://hg.python.org/releasing/3.4/file/tip/Lib/socket.py#l274

```python
# for socket.socket
    if os.name == 'nt':
        def get_inheritable(self):
            return os.get_handle_inheritable(self.fileno())
        def set_inheritable(self, inheritable):
            os.set_handle_inheritable(self.fileno(), inheritable)
    else:
        def get_inheritable(self):
            return os.get_inheritable(self.fileno())
        def set_inheritable(self, inheritable):
            os.set_inheritable(self.fileno(), inheritable)
```
and since `os.(get|set)_inheritance` and `socket.socket.(get|set)_inheritance` were added both in `3.4`...

```
if hasattr(s, 'set_inheritable'):
    s.set_inheritable(True)
```

should do it

**Comment by mortodeg** [comment]
Confirmed on 3.4 and 3.5. Flask with debug enabled does not start on Windows due to this.

**Comment by mitsuhiko** [comment]
I fixed this on the maintenance branch but I need to check on a windows machine if that actually fixes it.

**Comment by Socialery** [comment]
It stops the error occurring at least, whether the socket is actually inherited or not, don't know. But I think it'd be safe to assume so

**Comment by mitsuhiko** [comment]
Well, if the server runs then it's good :D
