### ISSUE TITLE
Bad URL in documentation (http://paste.pocoo.org/)

### ISSUE THREAD

**Issue by brooksc** [mitsuhiko/werkzeug#831]
http://werkzeug.pocoo.org/docs/dev/debug/ has a link to http://paste.pocoo.org/ but as of Dec 16 this returns 

Content Gone

The previous content on this page no longer exists because we retired the service. You might however be able to find the sourcecode that powered it with a search on Google.

Sorry for the inconvenience caused.

— The Pocoo Team

**Comment by mitsuhiko** [comment]
That's fixed.
