### ISSUE TITLE
Big performance penalty in 0.11 in BuildError

### ISSUE THREAD

**Issue by xcash** [mitsuhiko/werkzeug#835]
I know this is an infrequent issue.

Our flask-based framework is localized. Urls are localized too. Sometimes urls do not need to be localized.
To deal with this we created a `lurl_for` function that mimics standard `url_for` but search if there are localized urls available. If not it defaults to default language or unlocalized url.
To achieve this we use custom endpoints.

```python
@bp.route("en/our-services", endpoint='services_en')
@bp.route("it/i-nostri-servizi", endpoint='services_it')
@login_required
def services():
  ...
```

our custom localized url_for function is as follows:

```python
def lurl_for(ep, language=None, **kwargs):
	if language:
		# language override
		# try the url with *language*, then without
		# index_it variation
		try:
			return url_for(ep[:-2]+language, **kwargs)
		except Exception:
			pass
		# index variation
		try:
			return url_for(ep+'_'+language, **kwargs)
		except Exception:
			return url_for(ep, **kwargs)
	
	# no override, current language
	try:
		return url_for(ep+'_'+g.language, **kwargs)
	except BuildError:
		return url_for(ep, **kwargs)
```

As you can see we **abuse** the  `BuildError`

The worst case had a penalty of about 6 to 10ms.

Now, starting from 0.11, we had penalties at peak from 5x to 10x slower!
This is beacuse the auto-suggestion system in BuildError is useful but very slow when you expect failures.

I read @Frozenball implemented this and it's a great and useful feature.
But I'm asking if possible to at least be able to turn it off programmatically (like another  _keyword argument in url_for).

Werkzeug should be lightining fast at least in production. And in production we don't need autosuggesting errors.
We use flask for speed. As we develop also on AppEngine where slowness equals costs :D

Please let me know if you have a workaround (now we're on 0.10.x but it's not ideal to stay on old versions) or if i misread something.. :)

As always, thanks for the great work on Werkzeug.

**Comment by Frozenball** [comment]
Well, BuildError could be modified so the suggestions are lazyloaded.

**Comment by xcash** [comment]
@Frozenball that would be a very elegant solution! :+1: 
run fast and raise fast! :D

**Comment by mitsuhiko** [comment]
Absolutely correct. I'm not sure how I failed to review that commit but i'm going to fi this.  This should only be done if someone stringifies out the error.

**Comment by xcash** [comment]
@mitsuhiko Hmm... after 1+ year this still seems unresolved. And your commit seems unmerged.

**Comment by RonnyPfannschmidt** [comment]
@xcash acording to the gh ux it was merged in 2015 *and* is in master

**Comment by xcash** [comment]
@RonnyPfannschmidt you're right.. i should've checked it better. But even if i can see the correct code here in GH but the last pip version 0.11.15 still shows the old BuildError implementation...  any idea?

**Comment by roganov** [comment]
@mitsuhiko Can we please have a release with this patch?

**Comment by untitaker** [comment]
Sorry, it was in fact me who merged the original PR. On it!

**Comment by untitaker** [comment]
Ok, so nevermind that commit reference, I just released 0.12

**Comment by roganov** [comment]
@untitaker Thanks a lot, I can finally remove monkey patching.

**Comment by xcash** [comment]
Thanks a lot Markus! :)

2017-03-10 12:25 GMT+01:00 Yegor Roganov <notifications@github.com>:
