### ISSUE TITLE
has_likely_buggy_unicode_filesystem

### ISSUE THREAD

**Issue by Arti3DPlayer** [mitsuhiko/werkzeug#843]
I send post data to my flask project and receive:
```/home/.virtualenvs/project/local/lib/python2.7/site-packages/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ANSI_X3.4-1968'
BrokenFilesystemWarning)```

I change system encoding to UTF-8

```
>>> import sys
>>> sys.getfilesystemencoding()
'UTF-8'

>>> print sys.platform
linux2
```

Now i don't receive warning, but the half of data is not come...

**Comment by untitaker** [comment]
@Arti3DPlayer Please provide more information. Basically the only thing in your report that indicates that there might be an issue with Werkzeug is:

>but the half of data is not come...

**Comment by mitsuhiko** [comment]
I will close this. This is an environment issue and with regards to what "half data is not come" means this should be reopened with more information.

**Comment by vhosakot** [comment]
I saw the `BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem` error too. After digging the code, I saw that this error is harmless and just a warning in `/usr/local/lib/python2.7/dist-packages/werkzeug/filesystem.py`:

            warnings.warn(
                'Detected a misconfigured UNIX filesystem: Will use UTF-8 as '
                'filesystem encoding instead of {0!r}'.format(rv),
                BrokenFilesystemWarning)

So, I would not worry about the `BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem` warning.
