### ISSUE TITLE
Routing rule globbing match

### ISSUE THREAD

**Issue by kenshin54** [mitsuhiko/werkzeug#846]
Is it able to define the rule like this:

```python
url_map = Map([
    Rule('/test*', endpoint='test')
])
```

So the urls below can be matched to the rule:

```
www.example.com/test
www.example.com/test/x
www.example.com/test/y/z
```

**Comment by davidism** [comment]
Use the [`path`](http://werkzeug.pocoo.org/docs/0.11/routing/#werkzeug.routing.PathConverter) converter.

    Rule('/test/<path:rest>')

**Comment by kenshin54** [comment]
@davidism Thanks for reply. The `path` only works for the urls like `www.example.com/test/x` and `www.example.com/test/y/z'`, but not the first one `www.example.com/test`. I have to define two rules to match all of them like this:

```python
url_map = Map([
    Rule('/test', endpoint='test'),
    Rule('/test/<path:rest>', endpoint='test')
])
```

Is there an one rule solution available?

**Comment by RonnyPfannschmidt** [comment]
you could create a own converter that has a more greedy regex, i suggest not to do so

**Comment by kenshin54** [comment]
@RonnyPfannschmidt Got it. Thanks.
