### ISSUE TITLE
About JSON encoding in werkzeug.utils.py

### ISSUE THREAD

**Issue by caiz** [mitsuhiko/werkzeug#847]
def get_content_type(mimetype, charset):
    """Returns the full content type string with charset for a mimetype.
    If the mimetype represents text the charset will be appended as charset
    parameter, otherwise the mimetype is returned unchanged.
    :param mimetype: the mimetype to be used as content type.
    :param charset: the charset to be appended in case it was a text mimetype.
    :return: the content type.
    """
    if mimetype.startswith('text/') or \
       mimetype == 'application/xml' or \
       (mimetype.startswith('application/') and
            mimetype.endswith('+xml')):
        mimetype += '; charset=' + charset
    return mimetype

I was just beginning to touch this, have a encoding problems.
Why not judge  “mimetype == 'application/json' ”?

**Comment by untitaker** [comment]
JSON is always UTF-8.

**Comment by jacktan1991** [comment]
@caiz there is another discussion: https://github.com/request/request/issues/383, and more details about JSON charset: http://tools.ietf.org/html/rfc4627#section-3

**Comment by caiz** [comment]
thank you for your help.
