### ISSUE TITLE
All the Travis builds are broken...

### ISSUE THREAD

**Issue by frank-borkin** [mitsuhiko/werkzeug#851]
Every new pull request fails due to stylecheck failures in existing code.

**Comment by remram44** [comment]
#861 makes the tests pass again.

**Comment by frank-borkin** [comment]
Nope. I've not touched either of the following files:

3.04s$ make stylecheck
flake8
./werkzeug/script.py:320:5: E301 expected 1 blank line, found 0
./werkzeug/security.py:214:73: W291 trailing whitespace
make: *** [stylecheck] Error 1

**Comment by remram44** [comment]
#861 will make them pass again *once it's merged* ;)

The style issues were introduced by 551cf69b and a6ba7395.

**Comment by remram44** [comment]
Can't wait for the tests results (Travis is slow today), if [the tests don't pass](https://travis-ci.org/mitsuhiko/werkzeug/builds/106820114), try #865.
