### ISSUE TITLE
Why headers.extend() rather than headers.update()?

### ISSUE THREAD

**Issue by brainix** [mitsuhiko/werkzeug#860]
Browsing the source code, I noticed that [`Headers` defines an `extend()` method](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/datastructures.py#L1028-L1041).  Why is this method called `extend()` rather than `update()`?  On a dict-like object, I'd expect an `update()` method, though I'm probably missing something.  Thanks!

**Comment by mitsuhiko** [comment]
Because headers is a list.

**Comment by brainix** [comment]
Doh.  Thank you for teaching me the ways yet again, @mitsuhiko.  :100:
