### ISSUE TITLE
reloader using thread

### ISSUE THREAD

**Issue by blackrosezy** [mitsuhiko/werkzeug#869]
Currently reloader is using python subprocess module to restart the process. But this will not work in the restricted environment such as ios. Can we have an option to use thread instead of subprocess? Thanks!

**Comment by untitaker** [comment]
That is not technically possible. You need to reload sys.modules as well.

On 8 February 2016 07:38:49 CET, Mohd Rozi <notifications@github.com> wrote:
>Currently reloader is using python subprocess module to restart the
>process. But this will not work in the restricted environment such as
>ios. Can we have an option to use thread instead of subprocess? Thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/werkzeug/issues/869

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
