### ISSUE TITLE
secure_filename in werkzeug.util is problematic when the file name isnon-ASCII characters

### ISSUE THREAD

**Issue by robinclark007** [mitsuhiko/werkzeug#883]
if the file name is non-ASCII characters
then using secure_filename will result become wired

so How can I solve this problem
If I'm going to do my own secure_filename 
where should I put my code>>>>

**Comment by untitaker** [comment]
This is intended behavior to fend off a larger range of  (since many unicode chars look alike).

**Comment by robinclark007** [comment]
@untitaker Does that mean I have to  write a secure_filename function by myself,
cause I can't control the filename the user uploaded.

**Comment by untitaker** [comment]
Could you talk a bit more about your situation where you can't forbid unicode?

On 30 March 2016 09:49:23 CEST, tyan4g <notifications@github.com> wrote:
>@untitaker Does that mean I have to  write a secure_filename function
>by myself,
>cause I can't control the filename the user uploaded.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/werkzeug/issues/883#issuecomment-203300329

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
